# Generated by Django 5.0.4 on 2024-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finovate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
